### ISSUE TITLE
[Gssoc'21] bug in login

### ISSUE THREAD

**Issue by arpit456jain** [vigneshshettyin/Bulk-Mailer#100]
### **Describe the bug**
When the user is logged in there should be his name with logout option

https://user-images.githubusercontent.com/55352601/114269749-3dba8200-9a26-11eb-95ec-25719ca2cf56.mp4

**Comment by vigneshshettyin** [comment]
Okay, u can add user name and avatar there. @arpit456jain

**Comment by arpit456jain** [comment]
> Okay, u can add user name and avatar there. @arpit456jain

yes @vigneshshettyin I had done this and made a PR kindly review it and these same labels to it.

**Comment by vigneshshettyin** [comment]
Okay
