### ISSUE TITLE
[Gssoc'21] Not good for mobile view

### ISSUE THREAD

**Issue by arpit456jain** [vigneshshettyin/Bulk-Mailer#101]
### **Describe the bug**
Every thing is just too small for mobile version 
<img width="960" alt="p1" src="https://user-images.githubusercontent.com/55352601/114270083-1bc1ff00-9a28-11eb-9b28-33021a6c478b.png">

i want to make them large and responsive like this . I have to write media queries.
<img width="960" alt="sole" src="https://user-images.githubusercontent.com/55352601/114270116-4613bc80-9a28-11eb-812f-e9925c21cc72.png">

**Comment by vigneshshettyin** [comment]
Okay @arpit456jain

**Comment by arpit456jain** [comment]
@vigneshshettyin there is a lot of use of this in the website (wrong use of comment brackets)
<img width="960" alt="p1" src="https://user-images.githubusercontent.com/55352601/114293093-ef05fa00-9ab0-11eb-948a-65987098f5a1.png">

can I correct them or they are here intentionally.??

**Comment by vigneshshettyin** [comment]
Correct it @arpit456jain

**Comment by arpit456jain** [comment]
ok @vigneshshettyin

**Comment by arpit456jain** [comment]
@vigneshshettyin kindly review my PR

**Comment by vigneshshettyin** [comment]
> @vigneshshettyin kindly review my PR

Okay @arpit456jain
