### ISSUE TITLE
[Gssoc'21] Adding Dark mode in website

### ISSUE THREAD

**Issue by arpit456jain** [vigneshshettyin/Bulk-Mailer#105]
### Is your feature request related to a problem? Please describe.
I would like to to add dark mode in the website

**Comment by vigneshshettyin** [comment]
> ### Is your feature request related to a problem? Please describe.
> I would like to to add dark mode in the website
> 
> 
> 

Yes @arpit456jain

**Comment by arpit456jain** [comment]
@vigneshshettyin just wanted to ask 1 question can i use the same toggle button which i used in your other project or i should make a new one?

**Comment by vigneshshettyin** [comment]
> @vigneshshettyin just wanted to ask 1 question can i use the same toggle button which i used in your other project or i should make a new one?

Use this https://dev.to/joyshaheb/light-dark-mode-toggle-button-using-1-variable-2021-css-js-13l

**Comment by arpit456jain** [comment]
Ok

**Comment by mohammedjameel24** [comment]
assign me @vigneshshettyin

**Comment by vigneshshettyin** [comment]
> assign me @vigneshshettyin

Hey, @mohammedjameel24 @arpit456jain is currently working on this issue.

**Comment by arpit456jain** [comment]
> > @vigneshshettyin just wanted to ask 1 question can i use the same toggle button which i used in your other project or i should make a new one?
> 
> Use this https://dev.to/joyshaheb/light-dark-mode-toggle-button-using-1-variable-2021-css-js-13l

@vigneshshettyin I am finding some difficulty in using this toggle button  when i am placing it in landing.html it creating problem.

Although its js code is also very poorly written , when i refresh it always back in white mode , but i changed it and make it perfect but still when i am placing it in main page it disturbs whole page currently i have added this toggle button 
<img width="960" alt="mail" src="https://user-images.githubusercontent.com/55352601/114852422-62d13b00-9e00-11eb-8e11-20b3569e2362.png">

**Comment by arpit456jain** [comment]
@vigneshshettyin check it if its ok then fine otherwise I will try it once again....

**Comment by vigneshshettyin** [comment]
> @vigneshshettyin check it if its ok then fine otherwise I will try it once again....

Yes it is fine @arpit456jain

**Comment by arpit456jain** [comment]
> > @vigneshshettyin check it if its ok then fine otherwise I will try it once again....
> 
> Yes it is fine @arpit456jain

ok @vigneshshettyin writing the css for dark mode 

should i add this to login/sign up in this issue or create  a new issue for that ?

**Comment by vigneshshettyin** [comment]
Do it in this issue itself i will move this issue to level 3 @arpit456jain

**Comment by arpit456jain** [comment]
> Do it in this issue itself i will move this issue to level 3 @arpit456jain

ok @vigneshshettyin

**Comment by arpit456jain** [comment]
@vigneshshettyin kindly review my PR its done finally
