### ISSUE TITLE
Confirmation before logout

### ISSUE THREAD

**Issue by arpit456jain** [vigneshshettyin/Bulk-Mailer#109]
I would like to add a modal for confirmation of logout. Like when user clicks on logout a modal will open and it will asks user 

Are you sure you want to logout !! 
Then use can click ok or cancel it

**Comment by vigneshshettyin** [comment]
That's cool. I recommend you use Sweet Alert (`https://sweetalert.js.org/`)

**Comment by arpit456jain** [comment]
@vigneshshettyin kindly review my PR

**Comment by vigneshshettyin** [comment]
Okay
