### ISSUE TITLE
replacing confirmation in dashboard

### ISSUE THREAD

**Issue by arpit456jain** [vigneshshettyin/Bulk-Mailer#112]
### Is your feature request related to a problem? Please describe.
I would like to replace the confirmation in dashboard from bootstrap modal to sweet alaet

**Comment by arpit456jain** [comment]
@vigneshshettyin please add labels to my previous PR and don't revert it if there is any changes has to be done I will do it in the PR for this issue

**Comment by vigneshshettyin** [comment]
Okay

**Comment by arpit456jain** [comment]
@vigneshshettyin its done check it
