### ISSUE TITLE
Create a link to go to dashboard from the homepage.

### ISSUE THREAD

**Issue by devRawnie** [vigneshshettyin/Bulk-Mailer#114]
### Is your feature request related to a problem? Please describe.
Once a user is logged in, there is no option to go to the Dashboard from there. I have attached a screenshot for reference,

### Describe the solution you'd like
In the menu, which is opened by clicking the username, I would like to add a link to the dashboard

### Describe how this feature will be useful to our readers.
User can easily navigate to the dashboard from the Main page, 

![Screenshot from 2021-04-17 14-00-07](https://user-images.githubusercontent.com/43227329/115107049-216a9800-9f86-11eb-8505-0f17eee470eb.png)

**Comment by vigneshshettyin** [comment]
> ### Is your feature request related to a problem? Please describe.
> Once a user is logged in, there is no option to go to the Dashboard from there. I have attached a screenshot for reference,
> 
> ### Describe the solution you'd like
> In the menu, which is opened by clicking the username, I would like to add a link to the dashboard
> 
> ### Describe how this feature will be useful to our readers.
> User can easily navigate to the dashboard from the Main page, 
> 
> ![Screenshot from 2021-04-17 14-00-07](https://user-images.githubusercontent.com/43227329/115107049-216a9800-9f86-11eb-8505-0f17eee470eb.png)
> 
> 

Okay

**Comment by devRawnie** [comment]
I have completed the feature. Kindly go through the same
