### ISSUE TITLE
Contact us section

### ISSUE THREAD

**Issue by arpit456jain** [vigneshshettyin/Bulk-Mailer#116]
I would like to add a contract form on a separate page

**Comment by vigneshshettyin** [comment]
Cool, @arpit456jain. Also, post the response to the backend dashboard.

**Comment by arpit456jain** [comment]
> Cool, @arpit456jain. Also, post the response to the backend dashboard.

@vigneshshettyin i am not getting what do you mean by back-end dashboard.

You mean to say database or something else ??

**Comment by vigneshshettyin** [comment]
Yup, to the DB and create a table to view all the responses @arpit456jain

**Comment by arpit456jain** [comment]
> Yup, to the DB and create a table to view all the responses @arpit456jain

Ok but can i work on creating table to view all responses in another issue ?

**Comment by vigneshshettyin** [comment]
Okay, cool @arpit456jain

**Comment by arpit456jain** [comment]
@vigneshshettyin  is there any way to check data is stored or not although i am 99% sure the data is saved in database successfully

**Comment by vigneshshettyin** [comment]
> @vigneshshettyin  is there any way to check data is stored or not although i am 99% sure the data is saved in the database successfully

Yup using DB browser. @arpit456jain 
https://sqlitebrowser.org/

**Comment by arpit456jain** [comment]
> > @vigneshshettyin  is there any way to check data is stored or not although i am 99% sure the data is saved in the database successfully
> 
> Yup using DB browser. @arpit456jain
> https://sqlitebrowser.org/

thanks @vigneshshettyin kindly review my PR and add same labels to it

**Comment by vigneshshettyin** [comment]
Done @arpit456jain
