### ISSUE TITLE
Contact Table in Dashboard for admin

### ISSUE THREAD

**Issue by arpit456jain** [vigneshshettyin/Bulk-Mailer#119]
### Is your feature request related to a problem? Please describe.
Contact Table in Dashboard for admin like others

**Comment by arpit456jain** [comment]
@vigneshshettyin kindly assign me this.

**Comment by vigneshshettyin** [comment]
> @vigneshshettyin kindly assign me this.

Okay, assigning to you. @arpit456jain

**Comment by arpit456jain** [comment]
https://user-images.githubusercontent.com/55352601/115350236-7e5a8e00-a1d2-11eb-8c2e-6afafd499f08.mp4

**Comment by arpit456jain** [comment]
@vigneshshettyin is it ok ?
I have handle the admin access

**Comment by arpit456jain** [comment]
ok making the PR
