### ISSUE TITLE
Wave in Footer

### ISSUE THREAD

**Issue by arpit456jain** [vigneshshettyin/Bulk-Mailer#125]
I had added this wave in footer and i would like to make a PR for this
<img width="960" alt="wave" src="https://user-images.githubusercontent.com/55352601/115555111-ca89f900-a2cc-11eb-9425-f8bc9f81d067.png">

**Comment by vigneshshettyin** [comment]
Yeah @arpit456jain

**Comment by arpit456jain** [comment]
ok making the PR
