### ISSUE TITLE
QA : Need of code linter and Formatter

### ISSUE THREAD

**Issue by Aryamanz29** [vigneshshettyin/Bulk-Mailer#130]
- Need a workflow that ensures every contributor should follow the PEP-8 style guide for python code.
- We can use `flake8` for linting and `Black` for formatting source code.
- Also this workflow runs on every PR which ensures the code follows PEP8 standard or not.

**Comment by vigneshshettyin** [comment]
Okay @Aryamanz29

**Comment by Aryamanz29** [comment]
@vigneshshettyin  How to set up the backend for this repo?

**Comment by Aryamanz29** [comment]
I'm unable to register as a new user, it throws an error `sqlalchemy.exc.OperationalError`

**Comment by vigneshshettyin** [comment]
> I'm unable to register as a new user, it throws an error `sqlalchemy.exc.OperationalError`

https://github.com/vigneshshettyin/Bulk-Mailer/discussions/36#discussioncomment-487147
