### ISSUE TITLE
Profile page template

### ISSUE THREAD

**Issue by TrojanTarun** [vigneshshettyin/Bulk-Mailer#134]
### Is your feature request related to a problem? Please describe.
User's unable to see or customize profile on the dashboard.

### Describe the solution you'd like
I want to add a user profile page at the dashboard.

**Comment by vigneshshettyin** [comment]
Okay, @TrojanTarun

**Comment by srishtij2000** [comment]
Can I work on this issue?

**Comment by vigneshshettyin** [comment]
> Can I work on this issue?

Hey, @srishtij2000 this issue was already been assigned to @TrojanTarun . I would rather recommend you to create the same kind of issue for my other project which is also part of GSSOC'21 (https://github.com/vigneshshettyin/Flask-Generate-Certificate). I'll assign that issue to you. 

Happy coding!
