### ISSUE TITLE
Use of .env instead of import.json

### ISSUE THREAD

**Issue by ashutoshkrris** [vigneshshettyin/Bulk-Mailer#141]
### Is your feature request related to a problem? Please describe.
A clear and concise description of what the problem is. 
For now, we have kept all the secrets in a import.json file which is not a standard way to store those data.

### Describe the solution you'd like
The standard way to store those data is to use a .env file which will be helpful during deployment as well.

### Describe how this feature will be useful to our readers.
A clear and concise description of how this feature will be useful for our  other readers.

### Additional context

<hr/>

**Comment by vigneshshettyin** [comment]
Yup, @ashutoshkrris assigning to you.
