### ISSUE TITLE
Replace Default Messages with SweetAlert and Simple-Notify

### ISSUE THREAD

**Issue by ashutoshkrris** [vigneshshettyin/Bulk-Mailer#143]
### Is your feature request related to a problem? Please describe.
A clear and concise description of what the problem is. 
Currently, we are using default message flashing for showing messages.

### Describe the solution you'd like
Instead of using flashes which looks dull and boring, we can use SweetAlert and Simple-Notify as and when required.

### Describe how this feature will be useful to our readers.
A clear and concise description of how this feature will be useful for our  other readers.

### Additional context

<hr/>

**Comment by vigneshshettyin** [comment]
Yup, @ashutoshkrris assigning to you.
