### ISSUE TITLE
Admin Middleware

### ISSUE THREAD

**Issue by ashutoshkrris** [vigneshshettyin/Bulk-Mailer#145]
### Is your feature request related to a problem? Please describe.
A clear and concise description of what the problem is. 
Whenever we need to check if the user is admin or not, we need to write the same code again and again.

### Describe the solution you'd like
We can use admin middleware to check if the current logged in user is admin or not.

### Describe how this feature will be useful to our readers.
A clear and concise description of how this feature will be useful for our  other readers.

### Additional context

<hr/>

**Comment by vigneshshettyin** [comment]
Yup, @ashutoshkrris assigning to you.
