### ISSUE TITLE
Forgot Password

### ISSUE THREAD

**Issue by ashutoshkrris** [vigneshshettyin/Bulk-Mailer#148]
### Is your feature request related to a problem? Please describe.
A clear and concise description of what the problem is. 
Currently, forgot password is not implemented properly.

### Describe the solution you'd like
Forgot password can be implemented using verification links

### Describe how this feature will be useful to our readers.
A clear and concise description of how this feature will be useful for our  other readers.

### Additional context

<hr/>

**Comment by vigneshshettyin** [comment]
Yup, @ashutoshkrris assigning to you.
