### ISSUE TITLE
Landing page

### ISSUE THREAD

**Issue by data-charya** [vigneshshettyin/Bulk-Mailer#15]
Create a landing page with profiles of contributors using the following mockup as reference.
<br>
![Prototype](https://cdn.discordapp.com/attachments/701086382407549019/819201358712012810/Custom_Size_1.png)

![Specifications](https://cdn.discordapp.com/attachments/701086382407549019/819201352814821486/specs.png)

**Comment by Supriya1702** [comment]
I would like to contribute to this

**Comment by data-charya** [comment]
Cool i've assigned it to you.

**Comment by vigneshshettyin** [comment]
> I would like to contribute to this

@Supriya1702 it's been 2 days since we have assigned issue to you. You haven't updated anything regarding it. 

Kindly post your update as soon as possible.

**Comment by Supriya1702** [comment]
@vigneshshettyin I'm still working upon it, I'll surely make the updates ASAP

**Comment by vigneshshettyin** [comment]
> @vigneshshettyin I'm still working upon it, I'll surely make the updates ASAP

Cool

**Comment by TrojanTarun** [comment]
I would like to work on this issue.

**Comment by data-charya** [comment]
I have assigned the issue to you @TrojanTarun

**Comment by vigneshshettyin** [comment]
Done!
