### ISSUE TITLE
Add carousel to contributor section in landing page

### ISSUE THREAD

**Issue by vigneshshettyin** [vigneshshettyin/Bulk-Mailer#162]
### Is your feature request related to a problem? Please describe.
When contributors increase the page length automatically increase to avoid it, a carousel can be introduced to the contributors' section.

### Describe the solution you'd like
Implement carousel 

### Describe how this feature will be useful to our readers.
A clear and concise description of how this feature will be useful for our other readers.

### Additional context
Some carousel libraries 
1. https://swiperjs.com/
2. https://owlcarousel2.github.io/OwlCarousel2/
3. https://kenwheeler.github.io/slick/

<hr/>

**Comment by Sukriti-sood** [comment]
I would like to work on this.

**Comment by vigneshshettyin** [comment]
Yup, assigning this issue to you @Sukriti-sood .

**Comment by arpit456jain** [comment]
I am also interested in this issue

**Comment by vigneshshettyin** [comment]
Hi, @Sukriti-sood & @arpit456jain as both of you have commented I have assigned it to both of you. The first pr linked to this issue will be merged. 
Thanks!
