### ISSUE TITLE
Use Flask-Migrate to manage database

### ISSUE THREAD

**Issue by ashutoshkrris** [vigneshshettyin/Bulk-Mailer#165]
### Is your feature request related to a problem? Please describe.
A clear and concise description of what the problem is. 
Whenever we make change to the database, we need to delete the entire database and create a new one.

### Describe the solution you'd like
Instead of it, we can use Flask Migrate which gives us useful commands to migrate new changes

### Describe how this feature will be useful to our readers.
A clear and concise description of how this feature will be useful for our  other readers.

### Additional context

<hr/>

**Comment by vigneshshettyin** [comment]
Yup, @ashutoshkrris assigning this issue to you.
