### ISSUE TITLE
improve the dark mode

### ISSUE THREAD

**Issue by shettyraksharaj** [vigneshshettyin/Bulk-Mailer#171]
The dark mode only turn the main background black leaving the other elements the same making the page look displeasing.

The issue can be resolved by changing the color scheme of the elements appropriately.
![Screenshot 2021-05-06 230801](https://user-images.githubusercontent.com/50332765/117341598-f8239480-aebf-11eb-87cb-932d7b65f21f.png)
above screenshot is the current dark mode.

**Comment by AshuKV** [comment]
Can I work on this issue under GSSoC'21? Kindly assign it to me.

**Comment by vigneshshettyin** [comment]
Okay, @AshuKV assigning this issue to you.

**Comment by arpit456jain** [comment]
@AshuKV are you working on this issue ? its been 6 days

**Comment by vigneshshettyin** [comment]
Hey, @arpit456jain if you are interested you can take up

**Comment by arpit456jain** [comment]
ok i am on it . 
please assign me

**Comment by vigneshshettyin** [comment]
Okay @arpit456jain
