### ISSUE TITLE
Setting up Eslint in the project

### ISSUE THREAD

**Issue by subhangi2731** [vigneshshettyin/Bulk-Mailer#179]
I would like to lint the code and make the code look prettier by setting up Eslint in project. Please assign me this issue

**Comment by vigneshshettyin** [comment]
> @vigneshshettyin please assign me the issue

Okay, @subhangi2731 assigning this issue to you.

**Comment by Sukriti-sood** [comment]
@vigneshshettyin  Is this issue assignes or Can I work on this?

**Comment by vigneshshettyin** [comment]
You can work on it @Sukriti-sood. I'll assign it to you.

**Comment by subhangi2731** [comment]
@vigneshshettyin I am working on this please I will do pr by today

**Comment by vigneshshettyin** [comment]
First proposed PR if found valid will be approved @subhangi2731 @Sukriti-sood

**Comment by subhangi2731** [comment]
@vigneshshettyin please assign me too

**Comment by Sukriti-sood** [comment]
@vigneshshettyin  Just need to set up Lint to show errors or need to fix them.

**Comment by vigneshshettyin** [comment]
Just show errors. If you are interested you can raise pr. @Sukriti-sood
