### ISSUE TITLE
Auto Activation of the Email Account, once the user verifies his/her email address

### ISSUE THREAD

**Issue by devRawnie** [vigneshshettyin/Bulk-Mailer#19]
I am a GSSOC'21 Participant and I would like to work upon automating the Account Activation process which is dependent on Admin for the moment. Once the User verifies his/her email address, their account would be activated.

**Comment by vigneshshettyin** [comment]
Okay

**Comment by devRawnie** [comment]
Should I change the prompt "Now contact your organization head for account activation!" after the user signs up successfully to "Now verify your email address to activate your account"?
![image](https://user-images.githubusercontent.com/43227329/111040384-c6aac180-8458-11eb-831d-06ea78b39196.png)

**Comment by vigneshshettyin** [comment]
> Should I change the prompt "Now contact your organization head for account activation!" after the user signs up successfully to "Now verify your email address to activate your account"?
> ![image](https://user-images.githubusercontent.com/43227329/111040384-c6aac180-8458-11eb-831d-06ea78b39196.png)

Yes
