### ISSUE TITLE
Banner text responsiveness

### ISSUE THREAD

**Issue by sreetu** [vigneshshettyin/Bulk-Mailer#190]
### Is your feature request related to a problem? Please describe.
Banner text is not completely visible in mobile view 

### Describe the solution you'd like
To make banner text responsive

### Additional context

![Screenshot (1128)](https://user-images.githubusercontent.com/72204621/118640453-9dab0200-b7f6-11eb-8b0c-dfc8cdd60653.png)

<hr/>

**Comment by vigneshshettyin** [comment]
Okay, @sreetu assigning this issue to you.
