### ISSUE TITLE
Difference in All Sections

### ISSUE THREAD

**Issue by Sukriti-sood** [vigneshshettyin/Bulk-Mailer#206]
## **Describe the bug**

1.  There is lot of Mismatch in fonts of about section and rest of section of The Page and Only About Sections looks pleasant
2.  Mentors and COntributors sections cards need to be customized Sizes of logos and images need Modification

![BulkMailer](https://user-images.githubusercontent.com/55010599/119377662-00126f80-bcdb-11eb-9b76-6fa7d59d89b6.png)

**Comment by vigneshshettyin** [comment]
Okay

**Comment by arpit456jain** [comment]
I am also interested in this issue

**Comment by vigneshshettyin** [comment]
> I am also interested in this issue

@Sukriti-sood is working on it.
