### ISSUE TITLE
Not Responsive

### ISSUE THREAD

**Issue by Sukriti-sood** [vigneshshettyin/Bulk-Mailer#208]
Website is Responsive But First section About is different ,content of this mismatching the height od section , this is giving bad user Experience
![screencapture-127-0-0-1-5000-2021-05-24-21_59_59](https://user-images.githubusercontent.com/55010599/119378112-7f07a800-bcdb-11eb-8351-8a8d0c72421c.png)

**Comment by vigneshshettyin** [comment]
Okay

**Comment by vigneshshettyin** [comment]
> I am also interested in this issue

@Sukriti-sood is working on it.
