### ISSUE TITLE
Customize Scroll Bar

### ISSUE THREAD

**Issue by Sukriti-sood** [vigneshshettyin/Bulk-Mailer#214]
Customize Scrollbar

**Comment by vigneshshettyin** [comment]
> Customize Scrollbar

Add custom scrollbar to the dashboard as well. @Sukriti-sood

**Comment by vigneshshettyin** [comment]
Hey, @Sukriti-sood I will raise the issue label to level 3 pls do rectify the following errors add media queries to navbar elements also check for text responsiveness. 

![Screenshot_20210528-203912.png](https://user-images.githubusercontent.com/77713888/120004874-e764cb00-bff4-11eb-9467-b82e7e2c767a.png)

![Screenshot_20210528-203920.png](https://user-images.githubusercontent.com/77713888/120004893-ecc21580-bff4-11eb-8e63-63eb71b90530.png)

**Comment by Sukriti-sood** [comment]
@vigneshshettyin Ook Wil Do,

**Comment by vigneshshettyin** [comment]
Hey, @Sukriti-sood pls make all pr's by tomorrow

**Comment by arpit456jain** [comment]
hey @vigneshshettyin can I work on the responsiveness of navbar elements i will make sure of responsiveness of every element on home page .
I need some lvl3 issues urgently

**Comment by vigneshshettyin** [comment]
> hey @vigneshshettyin can I work on the responsiveness of navbar elements i will make sure of responsiveness of every element on home page .
> I need some lvl3 issues urgently 

No, this issue is already assigned to @Sukriti-sood  

@arpit456jain

**Comment by vigneshshettyin** [comment]
> hey @vigneshshettyin can I work on the responsiveness of navbar elements i will make sure of responsiveness of every element on home page .
> I need some lvl3 issues urgently 

You can work on improving the documentation like by adding file structure and all in Bulk Maiker and Certificate App if you are interested level 3 can be assigned @arpit456jain

**Comment by arpit456jain** [comment]
I had not much experience in making documentations ... any thing else other than this ?

**Comment by vigneshshettyin** [comment]
No @arpit456jain

**Comment by vigneshshettyin** [comment]
Hey, @Sukriti-sood pls make pr for this by today.

**Comment by Sukriti-sood** [comment]
> Hey, @Sukriti-sood pls make pr for this by today.

Ya I will , I added responsiveness code in that PR.

**Comment by Sukriti-sood** [comment]
@vigneshshettyin Did you checked ,Is website Responsiveness Fine Now, Or Still Need Changes.

**Comment by vigneshshettyin** [comment]
> @vigneshshettyin Did you checked ,Is website Responsiveness Fine Now, Or Still Need Changes.

It's responsive. Nice work @Sukriti-sood!!
