### ISSUE TITLE
Fixed Navbar

### ISSUE THREAD

**Issue by Sukriti-sood** [vigneshshettyin/Bulk-Mailer#215]
@vigneshshettyin Actually SIr ,Need Suggestion ,If it will look good in this website or not.

**Comment by vigneshshettyin** [comment]
> @vigneshshettyin Actually SIr ,Need Suggestion ,If it will look good in this website or not.

Yup, I am here to assist @Sukriti-sood

**Comment by Sukriti-sood** [comment]
@vigneshshettyin I just tried on browser , for fixing nav bar ,we need to change whole about section style , So , I just thing, I should drop this view,  Your suggestions ..?

**Comment by vigneshshettyin** [comment]
> @vigneshshettyin I just tried on browser , for fixing nav bar ,we need to change whole about section style , So , I just thing, I should drop this view,  Your suggestions ..?

Can you implement pull screen nav bar @Sukriti-sood just give a try

**Comment by Sukriti-sood** [comment]
@vigneshshettyin Did you mean Full Screen ? Can you give an example

**Comment by vigneshshettyin** [comment]
> > @vigneshshettyin I just tried on browser , for fixing nav bar ,we need to change whole about section style , So , I just thing, I should drop this view,  Your suggestions ..?
> 
> Can you implement pull screen nav bar @Sukriti-sood just give a try 

Sure, https://codepen.io/tonkec/pen/gryZmg

@Sukriti-sood

**Comment by vigneshshettyin** [comment]
> @vigneshshettyin Did you mean Full Screen ? Can you give an example

Yup, typo

**Comment by Sukriti-sood** [comment]
@vigneshshettyin Oh you mean Sidebar Type.

**Comment by vigneshshettyin** [comment]
> @vigneshshettyin Oh you mean Sidebar Type.

Yup
