### ISSUE TITLE
Relate Organization & Group Tables.

### ISSUE THREAD

**Issue by vigneshshettyin** [vigneshshettyin/Bulk-Mailer#22]
Setup a relationship between organization and group table on condition (on delete cascade ) for the smooth functioning of the app.

**Comment by sk1122** [comment]
You want Organization Model to function as Group Model.

What I mean by this is we can send email to every employee of organization

**Comment by vigneshshettyin** [comment]
> You want Organization Model to function as Group Model.
> 
> What I mean by this is we can send email to every employee of organization

I didn't get you. Can you be little clear please.

**Comment by sk1122** [comment]
@vigneshshettyin What I mean by that is, Treat Organisation table as Group Table, So that we can treat Employees of Organisation as a Group
