### ISSUE TITLE
bug in homepage

### ISSUE THREAD

**Issue by Sukriti-sood** [vigneshshettyin/Bulk-Mailer#223]
I am very sorry , I didnot proverly make it responsive , Still I found a bug in responsive nature for this range of screen size

![Screenshot from 2021-05-31 21-13-34](https://user-images.githubusercontent.com/55010599/120217230-b3d4ab80-c255-11eb-9b43-be3c0dabd401.png)

**Comment by vigneshshettyin** [comment]
Okay

**Comment by vigneshshettyin** [comment]
Hey, @Sukriti-sood do you want to work on this ?

**Comment by Sukriti-sood** [comment]
> Hey, @Sukriti-sood do you want to work on this ?

Ya will try to complete in a day or two
