### ISSUE TITLE
Bug in Dashboard

### ISSUE THREAD

**Issue by Sukriti-sood** [vigneshshettyin/Bulk-Mailer#224]
![Screenshot_2021_0531_212109](https://user-images.githubusercontent.com/55010599/120217819-82101480-c256-11eb-9221-cf4856d779d4.jpg)
![Screenshot_2021_0531_212121](https://user-images.githubusercontent.com/55010599/120217859-8fc59a00-c256-11eb-9162-a654a31c8cd8.jpg)

For this screen size in Dashboard , dark button and name with dp are not visible correctly

Way to improved this:-
- Remove the name from the nab bar only display dp and decreasing the width of dark button and adding name of user to the dialog appeared on clicking dp

**Comment by vigneshshettyin** [comment]
Okay

**Comment by vigneshshettyin** [comment]
Hey, @Sukriti-sood do you want to work on this ?

**Comment by Sukriti-sood** [comment]
> Hey, @Sukriti-sood do you want to work on this ?

Yes
