### ISSUE TITLE
Email Templates

### ISSUE THREAD

**Issue by vigneshshettyin** [vigneshshettyin/Bulk-Mailer#23]
Design some simple email templates which can be used by business professionals, students, developers etc. 

This issue will not have any time period to close. Any number of participants can contribute to this issue.

**Comment by Athira2199** [comment]
@vigneshshettyin could specify what categories the mails come under like welcome mails, newsletter, offers etc.

**Comment by vigneshshettyin** [comment]
All categories are accepted. See to it that you upload your template here (https://github.com/vigneshshettyin/Bulk-Mailer/tree/master/landing%20page) and update the Template.md file with your template name, category, and your name.

**Comment by vigneshshettyin** [comment]
@Athira2199 any updates?
