### ISSUE TITLE
Tech Stack Update ( LOGO add ) 

### ISSUE THREAD

**Issue by rohan-kulkarni-25** [vigneshshettyin/Bulk-Mailer#25]
I will like to add tech stack logo used in our project this will make our project attractive !! Will start to work on this issue as soon as i get assigned !!  I am GSSOC participant

**Comment by vigneshshettyin** [comment]
Okay

**Comment by vigneshshettyin** [comment]
> I will like to add tech stack logo used in our project this will make our project attractive !! Will start to work on this issue as soon as i get assigned !! 

Are you a GSSOC'21 participant? 
If yes please mention it in your issues.

**Comment by rohan-kulkarni-25** [comment]
Which tech stack will you like to get updated ?

**Comment by vigneshshettyin** [comment]
> Which tech stack will you like to get updated ?

You are supposed to do research on it and update readme.md . Kindly do the same.
