### ISSUE TITLE
Problem with a registration

### ISSUE THREAD

**Issue by WebaseGlobal** [vigneshshettyin/Bulk-Mailer#253]
When trying to sign up it says "Invalid Password. Please enter a valid password".

I was trying multiple passwords over 8 characters with small and big letters, special characters, and numbers. In all cases, I got the same error on "bulkmailer.cf" and "localhost" as well.

**Comment by vigneshshettyin** [comment]
Hey, @WebaseGlobal thanks for letting us know. Are you interested in working on this issue?

**Comment by vigneshshettyin** [comment]
Closing this issue as no response received from @WebaseGlobal
