### ISSUE TITLE
Forgot password giving error

### ISSUE THREAD

**Issue by SangeetR** [vigneshshettyin/Bulk-Mailer#29]
### **Describe the bug**
Getting error 302 at url "/forgot"

### **To Reproduce**
1. Go to 'login page'
2. Click on 'forgot password'
3. Open 'Developer Options'

### **Expected behavior**
I was hoping to see reset password page "forgot-password.html".

**Comment by SangeetR** [comment]
Assign me as gssoc21 participate i would love to solve this
and please add level tag also

**Comment by vigneshshettyin** [comment]
> ### **Describe the bug**
> Getting error 302 at url "/forgot"
> 
> ### **To Reproduce**
> Steps to reproduce the behavior:
> 
> 1. Go to 'login page'
> 2. Click on 'forgot password'
> 3. Open 'Developer Options'
> 4. See error
> 
> ### **Expected behavior**
> I was hoping to see reset password page "forgot-password.html".

Kindly share a screenshot of the error 302 @SangeetR

**Comment by SangeetR** [comment]
![Bulk-Mailer error 302](https://user-images.githubusercontent.com/32015811/111057169-3e094100-84ab-11eb-98aa-87c932754280.png)

**Comment by vigneshshettyin** [comment]
Cool, I have assigned it to you.
