### ISSUE TITLE
Link the tickmarks color on activation and deactivation of the accounts to green and red correspondingly.

### ISSUE THREAD

**Issue by devRawnie** [vigneshshettyin/Bulk-Mailer#31]
In the Users tab, the Activate/Deactivate column has one green tickmark only for both activated and deactivated accounts. I would like to update the HTML code such that for deactivated accounts, the color changes to red. Also, I am a GSSOC'21 Participant and would request you to add the same label.

**Comment by vigneshshettyin** [comment]
Okay. Assigning to you.
