### ISSUE TITLE
Use Github pages feature

### ISSUE THREAD

**Issue by asimarise** [vigneshshettyin/Bulk-Mailer#34]
### **Describe the bug**
we can use GitHub pages features instead of using other hosting platforms

### **To Reproduce**
A contributor can fork the repo and simply contribute to it and then host that fork GitHub repo through their Github account 
Its easy, fast, and hassle-free for a contributor and also to review for a Mentor

### **Expected behavior**
It will be easy for a contributor to get review his contribution 

### **Screenshots**
![image](https://user-images.githubusercontent.com/75176367/111210522-5b492700-85f3-11eb-847f-1a4afdf0f2f5.png)

**Comment by asimarise** [comment]
I would like to work on this Issue

**Comment by vigneshshettyin** [comment]
> I would like to work on this Issue

Okay.

**Comment by vigneshshettyin** [comment]
Closing this issue until further notice @asimaries
