### ISSUE TITLE
Add checkbox to issue templates

### ISSUE THREAD

**Issue by vigneshshettyin** [vigneshshettyin/Bulk-Mailer#41]
### What part(s) of the article would you like to see updated?
Add a checkbox in issue templates to select gssoc or other to distinguish contributors. This would also help mentors too to assign necessary labels.

**Comment by AshuKV** [comment]
Can I work on this issue under GSSoC'21? Kindly assign it to me.

**Comment by vigneshshettyin** [comment]
Okay

**Comment by vigneshshettyin** [comment]
Hey, @AshuKV it's a simple change. You have already taken 2 days. Today is your last day.
