### ISSUE TITLE
Display Profile photo

### ISSUE THREAD

**Issue by shettyraksharaj** [vigneshshettyin/Bulk-Mailer#5]
Currently, the display photo of the user is static. Make changes such that 
1.) user should be able to add a profile photo
2.) user should be able to update profile photo
3. the app should display the user photo when the user logged in to the dashboard.
4.) user should be able to delete a profile photo
that has a generic image for a profile photo. If the user has don't uploaded a photo assign a default photo

**Comment by jhamadhav** [comment]
Can you assign me this issue? I do my best to resolve it !

**Comment by jhamadhav** [comment]
> 
> 
> > Can you assign me this issue? I do my best to resolve it !
> 
> Okay, I hope the app is working fine for you now. Facing any errors let us know. @jhamadhav

Yes, If I face any issue I will definitely let you know.

On that note do we have a discord channel for this project, so we can communicate more seamlessly ?

**Comment by vigneshshettyin** [comment]
> > 
> > 
> > > Can you assign me this issue? I do my best to resolve it !
> > 
> > Okay, I hope the app is working fine for you now. Facing any errors let us know. @jhamadhav
> 
> Yes, If I face any issue I will definitely let you know.
> 
> On that note do we have a discord channel for this project, so we can communicate more seamlessly ?

Okay, GSSOC'21 have created a channel for bulk mailer in official GSSOC'21 discord server but access to it has been given to project admin and mentors for now. I'll have a word with the organizers let you if we can have a un-official discord channel.

**Comment by vigneshshettyin** [comment]
> > > > > Can you assign me this issue? I do my best to resolve it !
> > > > 
> > > > 
> > > > Okay, I hope the app is working fine for you now. Facing any errors let us know. @jhamadhav
> > > 
> > > 
> > > Yes, If I face any issue I will definitely let you know.
> > > On that note do we have a discord channel for this project, so we can communicate more seamlessly ?
> > 
> > 
> > Okay, GSSOC'21 have created a channel for bulk mailer in official GSSOC'21 discord server but access to it has been given to project admin and mentors for now. I'll have a word with the organizers let you if we can have a un-official discord channel.
> 
> Okay thanks, and please add assigned tags to the issues that has been assigned to anyone

Assigned.

**Comment by vigneshshettyin** [comment]
Kindly give your update @jhamadhav

**Comment by jhamadhav** [comment]
I am having my college exams will update next Saturday, will that be fine ?

**Comment by vigneshshettyin** [comment]
Nope, the issue will be unassigned.

**Comment by ashutoshkrris** [comment]
I can work on this @vigneshshettyin

**Comment by vigneshshettyin** [comment]
Yes. assigning to you.
