### ISSUE TITLE
Modal for editing groups

### ISSUE THREAD

**Issue by ashutoshkrris** [vigneshshettyin/Bulk-Mailer#51]
### Is your feature request related to a problem? Please describe.
A clear and concise description of what the problem is. 
There is no option to edit the groups as of now.

### Describe the solution you'd like
There should be a edit button for editing the groups. This button when clicked should open up a modal and everything should done using AJAX requests.

### Describe how this feature will be useful to our readers.
A clear and concise description of how this feature will be useful for our  other readers.

### Additional context

<hr/>

**Comment by vigneshshettyin** [comment]
Okay, Assigning it to you. @ashutoshkrris
