### ISSUE TITLE
Email and Password Validation

### ISSUE THREAD

**Issue by ashutoshkrris** [vigneshshettyin/Bulk-Mailer#52]
### Is your feature request related to a problem? Please describe.
A clear and concise description of what the problem is. 
There is no email and password validation for the login page.

### Describe the solution you'd like
Email and password validations should be there. This can be implemented with AJAX to check if the email address is registered or is valid or the password is strong enough.

### Describe how this feature will be useful to our readers.
A clear and concise description of how this feature will be useful for our  other readers.

### Additional context

<hr/>

**Comment by vigneshshettyin** [comment]
Okay, Assigning it to you. @ashutoshkrris
