### ISSUE TITLE
Email Template Selection using Ajax

### ISSUE THREAD

**Issue by ashutoshkrris** [vigneshshettyin/Bulk-Mailer#57]
### Is your feature request related to a problem? Please describe.
A clear and concise description of what the problem is. 
Currently, when we select the email template, the page redirects to other page according to the template id. Instead of redirecting, the template can be loaded in that page itself using AJAX request.

### Describe the solution you'd like
 Instead of redirecting, the template can be loaded in that page itself using AJAX request.

### Describe how this feature will be useful to our readers.
A clear and concise description of how this feature will be useful for our  other readers.

### Additional context

<hr/>

**Comment by vigneshshettyin** [comment]
> ### Is your feature request related to a problem? Please describe.
> A clear and concise description of what the problem is. 
> Currently, when we select the email template, the page redirects to other page according to the template id. Instead of redirecting, the template can be loaded in that page itself using AJAX request.
> 
> ### Describe the solution you'd like
> A clear and concise description of what you want to happen.
>  Instead of redirecting, the template can be loaded in that page itself using AJAX request.
> 
> ### Describe alternatives you've considered
> A clear and concise description of any alternative solutions or features you've considered.
> 
> ### Describe how this feature will be useful to our readers.
> A clear and concise description of how this feature will be useful for our  other readers.
> 
> ### Additional context
> Add any other context or screenshots about the feature request here.
> 
> <hr/>
> 

Go ahead! @ashutoshkrris
