### ISSUE TITLE
Link Landing Page with Contributors

### ISSUE THREAD

**Issue by ashutoshkrris** [vigneshshettyin/Bulk-Mailer#59]
### Is your feature request related to a problem? Please describe.
A clear and concise description of what the problem is. 
There is no landing page as of now.

### Describe the solution you'd like
As of now, the default home route goes to dashboard. Instead of this, there should be a landing page. 

### Describe how this feature will be useful to our readers.
A clear and concise description of how this feature will be useful for our  other readers.

### Additional context

<hr/>

**Comment by vigneshshettyin** [comment]
Yup, @ashutoshkrris you can work on it.
