### ISSUE TITLE
User List Visibility 

### ISSUE THREAD

**Issue by vigneshshettyin** [vigneshshettyin/Bulk-Mailer#6]
Have a need field called is_staff or is_superuser of a boolean data type in Organization DB model which is used to recognize a normal user or superuser or admin. The user list must be visible only to the admin users not to everyone. 
![Screenshot 2021-03-09 213809](https://user-images.githubusercontent.com/77713888/110501017-c68c8800-811f-11eb-9a9c-13ab0735fae1.png)

**Comment by vigneshshettyin** [comment]
Okay

**Comment by anjali7786** [comment]
Hii please tell me Can I make another dashboard for admin so that the user list is not shown to users other than admin?

**Comment by vigneshshettyin** [comment]
> Hii please tell me Can I make another dashboard for admin so that the user list is not shown to users other than admin?

Check for any other alternative. Have a variable called is_superuser you can distinguish user and admin using it.

**Comment by anjali7786** [comment]
Ok sir

**Comment by vigneshshettyin** [comment]
> Ok sir

Any updates @anjali7786 ??

**Comment by anjali7786** [comment]
Sir, I am not able to set up the database on my pc.

**Comment by vigneshshettyin** [comment]
@anjali7786 Kindly start a discussion our mentor team will help you out asap.

**Comment by anjali7786** [comment]
Ok sir

**Comment by vigneshshettyin** [comment]
Any updates @anjali7786  ??

**Comment by vigneshshettyin** [comment]
Closing this issue until further notice @anjali7786
