### ISSUE TITLE
Smart password validator

### ISSUE THREAD

**Issue by TrojanTarun** [vigneshshettyin/Bulk-Mailer#65]
Add a feature on the user registration page that may help users to validate the password field in a nice way.

**Comment by vigneshshettyin** [comment]
Hey, @TrojanTarun do you want to work on it?

**Comment by TrojanTarun** [comment]
Yes I want to work on it.

**Comment by vigneshshettyin** [comment]
Okay, assigning to you. @TrojanTarun

**Comment by vigneshshettyin** [comment]
Closing this issue till further consent. @TrojanTarun
