### ISSUE TITLE
Password format and visibility feature.

### ISSUE THREAD

**Issue by codebuzzer01** [vigneshshettyin/Bulk-Mailer#68]
### Is your feature request related to a problem? Please describe.
There is no restrictions or a format for password .

### Describe the solution you'd like
I would like to add a proper format for the password .

### Describe alternatives you've considered
An alternative feature which I would like to add is 'Show Password' feature while entering the password.

### Describe how this feature will be useful to our readers.
This feature will be helpful for users as they will get to know any typo errors while entering password or during confirmation of it.

<hr/>
I am a GSsOC'21  participant and would like to work on this issue . Kindly assign it to me.

**Comment by vigneshshettyin** [comment]
Yes, Assigning you @codebuzzer01

**Comment by codebuzzer01** [comment]
Hey @vigneshshettyin  will there be no label of level for it?

**Comment by vigneshshettyin** [comment]
It's there but it will be assigned once you make a pull request. @codebuzzer01

**Comment by codebuzzer01** [comment]
Ok thanks! @vigneshshettyin

**Comment by vigneshshettyin** [comment]
Due to no response received from your end, we are closing this issue. @codebuzzer01
