### ISSUE TITLE
Email and Password Validation

### ISSUE THREAD

**Issue by vigneshshettyin** [vigneshshettyin/Bulk-Mailer#7]
User email must be validated by using a regular expression.  A regular expression for emails can be found here (https://regexr.com/) Choose an apt one and implement it in the backend. Password also should meet the following conditions
1.) Password must be between 8 and 30 characters.
2.) Password must contain at least one uppercase, or capital, letter (ex: A, B, etc.).
3.) Password must contain at least one lowercase letter.
4.) Password must contain at least one numeric digit (ex: 0, 1, 2, 3, etc.)
5.) Password must contain at least one special character -for example, $, #, @, !,%,^,&,*,(,)
When these conditions are not followed apt flash messages must be invoked.

**Comment by devRawnie** [comment]
I would like to work on this. Could you please assign this to me.

**Comment by vigneshshettyin** [comment]
> I would like to work on this. Could you please assign this to me.

Okay

**Comment by devRawnie** [comment]
Just a heads up. I am a GSSOC'21 Participant. Could you please add the label gssoc21 to this issue.

**Comment by vigneshshettyin** [comment]
> Just a heads up. I am a GSSOC'21 Participant. Could you please add the label gssoc21 to this issue.

Sure. I will do.

**Comment by devRawnie** [comment]
I completed the code for validation of Email and Password. Kindly go through the following [https://github.com/vigneshshettyin/Bulk-Mailer/pull/10#issue-588459707](url) and if any changes are required, let me know. I would be more than happy to cater to the same.

**Comment by vigneshshettyin** [comment]
Hey ROHIT SHARMA!

Thanks for contributing. I have merged your PR.

**Comment by devRawnie** [comment]
Kindly, consider this PR #13 in which I modified the PASSWORD_REGEX field to include spaces as well which some people prefer.
