### ISSUE TITLE
Groups & Templates Visibility 

### ISSUE THREAD

**Issue by vigneshshettyin** [vigneshshettyin/Bulk-Mailer#8]
Currently, all groups and templates are visible to everyone. Make changes such that only groups and templates added by that particular user should be visible. But all groups and templates must be visible to the super user or admin user.

**Comment by SangeetR** [comment]
is there any superuser table yet i can see is only organization table

**Comment by vigneshshettyin** [comment]
> is there any superuser table yet i can see is only organization table

# We don't actually need a super user table in the current table ie organisation table have a extra field called is_staff or is_admin of boolean data type so, that a normal user and a admin user can be distinguished. 

Your task is to 

1.) Have a extra field is_staff or is_admin in organization table.
2.) Establish relationship between organization , group and template table. 
3.) Change the filtering conditions in query.

If you have more doubts start a discussion. Our mentor team will be always available to guide you. 

Thanks

**Comment by vigneshshettyin** [comment]
Hey, @SangeetR it's been 8 days since you haven't responded yet. Hence you will be unassigned.
