### ISSUE TITLE
Update requirements.txt

### ISSUE THREAD

**Issue by kanishka8276** [vigneshshettyin/Bulk-Mailer#85]
Adding oauthlib to requirements.txt
Gssoc21

**Comment by vigneshshettyin** [comment]
Hey, @kanishka8276 thanks for noticing it but we can't consider this type of pr for grading. I would recommend you to club this issue and (https://github.com/vigneshshettyin/Bulk-Mailer/issues/86). As your a beginner this could be considered.

**Comment by kanishka8276** [comment]
@vigneshshettyin  I updated the issue #86 as per your suggestion. Please assign it to me.

**Comment by vigneshshettyin** [comment]
> @vigneshshettyin I updated the issue #86 as per your suggestion. Please assign it to me.

Cool @kanishka8276
