### ISSUE TITLE
Adding view password option in login form

### ISSUE THREAD

**Issue by kanishka8276** [vigneshshettyin/Bulk-Mailer#87]
I will like to add option to view or hide password in login form.
Please assign this to me.
Gssoc21

**Comment by vigneshshettyin** [comment]
Yup, @kanishka8276 you can work on it.

**Comment by arpit456jain** [comment]
Can i work on this issue if there is no updates

**Comment by kanishka8276** [comment]
@arpit456jain  @vigneshshettyin  I am working on this issue and did the html css and javascript part, HTML CSS worked fine but the javaScript function is not working. Like on clicking on the check box the input type did not change and thus the password is not visible So, I am stuck.
Is it possible that I make PR for the HTML ,CSS part and then @arpit456jain  can work on the functioning?

**Comment by arpit456jain** [comment]
@vigneshshettyin kindly look into this

**Comment by vigneshshettyin** [comment]
@arpit456jain if your fine with this then yes. 
cc @kanishka8276

**Comment by arpit456jain** [comment]
Ok @kanishka8276  i will try to find the bug in your code and make it work otherwise i will write a fresh code.

**Comment by kanishka8276** [comment]
@arpit456jain  You can start with a fresh code.I just found out that I haven't stashed those changes and lost the code.
@vigneshshettyin Please assign this task to @arpit456jain . 
Sorry for the delay.

**Comment by vigneshshettyin** [comment]
Hey, @arpit456jain do you want to work on this issue?

**Comment by arpit456jain** [comment]
Yes ofcourse @vigneshshettyin kindly assign me this issue

**Comment by vigneshshettyin** [comment]
Okay, I'll assign this issue to you.

**Comment by arpit456jain** [comment]
@vigneshshettyin kindly review my PR.
