### ISSUE TITLE
[Gssoc'21] bug in login page

### ISSUE THREAD

**Issue by arpit456jain** [vigneshshettyin/Bulk-Mailer#89]
### **Describe the bug**
There is bug in login page  kindly see this video

https://user-images.githubusercontent.com/55352601/114188074-5ebb9e00-9966-11eb-87b5-80a2119bdcda.mp4

**Comment by vigneshshettyin** [comment]
Yup, your right. You can use custom validation or just add the required attribute in input tag. @arpit456jain

**Comment by arpit456jain** [comment]
@vigneshshettyin kindly review my PR
