### ISSUE TITLE
Email Verification 

### ISSUE THREAD

**Issue by Tom-Stack-UX** [vigneshshettyin/Bulk-Mailer#9]
Checking whether email address is genuine by generating a email to that email address which has a verification link such that it expires after some hours or seconds. 
For reference https://youtu.be/vF9n248M1yk

**Comment by vigneshshettyin** [comment]
Okay assigning it to you.

**Comment by devRawnie** [comment]
With reference to this Issue, How do I create the admin user for the project. So that I can activate other accounts. I am unable to login on the platform

**Comment by vigneshshettyin** [comment]
> With reference to this Issue, How do I create the admin user for the project. So that I can activate other accounts. I am unable to login on the platform
> 

Please check import.json file. Please change the admin email there to your email. You will get admin privileges.

**Comment by devRawnie** [comment]
On registration, one email is already being sent to the user. Should the email verification token be sent in the same email, or a separate email needs to be generated for verification?

**Comment by vigneshshettyin** [comment]
> On registration, one email is already being sent to the user. Should the email verification token be sent in the same email, or a separate email needs to be generated for verification?
> 

Hey 👋 

Sorry for delayed response. Send the token in the same email. Why to send two two emails.
