### ISSUE TITLE
[Gssoc'21 ]Enhancing the social media icons in footer

### ISSUE THREAD

**Issue by arpit456jain** [vigneshshettyin/Bulk-Mailer#90]
### Is your feature request related to a problem? Please describe.
I would like to add some cool and good looking social media icons in footer I had already done this .

It is looking like this now.
<img width="960" alt="footer" src="https://user-images.githubusercontent.com/55352601/114192468-25396180-996b-11eb-8a11-c31ac09f5bf1.png">

**Comment by arpit456jain** [comment]
@vigneshshettyin kindly assign me this issue so I can create a PR

**Comment by vigneshshettyin** [comment]
Okay. Assigning to you @arpit456jain

**Comment by arpit456jain** [comment]
@vigneshshettyin kindly review my PR
